---
- name: Install MySQL, Nginx, and PHP-FPM
  hosts: "{{ host }}"
  remote_user: root
  roles:
  - geerlingguy.mysql
  - chusiang.php7
  - geerlingguy.nginx
  - geerlingguy.certbot
  - sbaerlocher.wp-cli
  - joshualund.ufw
  - post-book
